# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build binary and container

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      publishType:
        required: true
        type: string

jobs:
  build-amd64:
    name: Build AMD64
    uses: ./.github/workflows/build-arch.yml
    with:
      publishType: ${{ inputs.publishType }}
      arch: amd64
      
  build-arm64:
    name: Build ARM64
    uses: ./.github/workflows/build-arch.yml
    with:
      publishType: ${{ inputs.publishType }}
      arch: arm64

  build-docs:
    uses: ./.github/workflows/docs-build.yml
