# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Fork, build, test, and publish new major/minor version.

permissions:
  contents: write
  packages: write

on:
  # Allow pipeline to be run manually.
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      publishType: prod

  publish-container:
    uses: ./.github/workflows/publish-container.yml
    needs:
    - build

  fork-branch:
    uses: ./.github/workflows/fork-branch.yml
    needs:
    - build

  # Publish GitHub release
